BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DDL';

    EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DML';
    EXECUTE IMMEDIATE 'ALTER SESSION SET PARALLEL_DEGREE_POLICY=AUTO';



    UPDATE /*+ NO_PARALLEL */ infop_stammdaten.vp set id = 0 where id = 5;
    SELECT /*+PARALLEL(4)*/ INFOP_FAHRPLAN.SEQ_ZIRKULAR.NEXTVAL FROM INFOP_IMPORT.hrdf_index_laufzeilen;
end;
/

